-- MySQL Script generated by MySQL Workbench
-- Sun Oct  5 08:46:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestaodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestaodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestaodb` DEFAULT CHARACTER SET utf8 ;
USE `gestaodb` ;

-- -----------------------------------------------------
-- Table `gestaodb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `hash_senha` CHAR(60) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`funcionarios` (
  `matricula` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_funcionarios_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gestaodb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`cargos` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`departamentos` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`cargos_internos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`cargos_internos` (
  `id_cargo_interno` INT NOT NULL,
  `salario_base` FLOAT NOT NULL,
  INDEX `fk_cargos_internos_cargos1_idx` (`id_cargo_interno` ASC) VISIBLE,
  PRIMARY KEY (`id_cargo_interno`),
  CONSTRAINT `fk_cargos_internos_cargos1`
    FOREIGN KEY (`id_cargo_interno`)
    REFERENCES `gestaodb`.`cargos` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`funcionarios_internos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`funcionarios_internos` (
  `matricula` VARCHAR(10) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  INDEX `fk_funcionarios_internos_funcionarios1_idx` (`matricula` ASC) VISIBLE,
  PRIMARY KEY (`matricula`),
  CONSTRAINT `fk_funcionarios_internos_funcionarios1`
    FOREIGN KEY (`matricula`)
    REFERENCES `gestaodb`.`funcionarios` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`contratos_internos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`contratos_internos` (
  `id_contrato_interno` INT NOT NULL AUTO_INCREMENT,
  `id_funcionario_interno` VARCHAR(10) NOT NULL,
  `id_cargo_interno` INT NOT NULL,
  `id_departamento` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `date_fim` DATE NOT NULL,
  PRIMARY KEY (`id_contrato_interno`),
  INDEX `fk_contratos_departamentos1_idx` (`id_departamento` ASC) VISIBLE,
  INDEX `fk_contratos_internos_cargos_internos1_idx` (`id_cargo_interno` ASC) VISIBLE,
  INDEX `fk_contratos_internos_funcionarios_internos1_idx` (`id_funcionario_interno` ASC) VISIBLE,
  CONSTRAINT `fk_contratos_departamentos1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `gestaodb`.`departamentos` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_internos_cargos_internos1`
    FOREIGN KEY (`id_cargo_interno`)
    REFERENCES `gestaodb`.`cargos_internos` (`id_cargo_interno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_internos_funcionarios_internos1`
    FOREIGN KEY (`id_funcionario_interno`)
    REFERENCES `gestaodb`.`funcionarios_internos` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`empresas_terceiras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`empresas_terceiras` (
  `id_empresa_terceira` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(50) NOT NULL,
  `cnpj` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_empresa_terceira`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`funcionarios_terceiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`funcionarios_terceiros` (
  `id_funcionario_terceiro` INT NOT NULL,
  `id_empresa_terceira` INT NOT NULL,
  INDEX `fk_funcionarios_terceirizados_funcionarios1_idx` (`id_funcionario_terceiro` ASC) VISIBLE,
  PRIMARY KEY (`id_funcionario_terceiro`),
  INDEX `fk_funcionarios_terceiros_empresas_terceiras1_idx` (`id_empresa_terceira` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_terceirizados_funcionarios1`
    FOREIGN KEY (`id_funcionario_terceiro`)
    REFERENCES `gestaodb`.`funcionarios` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionarios_terceiros_empresas_terceiras1`
    FOREIGN KEY (`id_empresa_terceira`)
    REFERENCES `gestaodb`.`empresas_terceiras` (`id_empresa_terceira`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`contratos_terceirizados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`contratos_terceirizados` (
  `id_contratos_terceirizados` INT NOT NULL AUTO_INCREMENT,
  `id_funcionario_terceiro` INT NOT NULL,
  `id_departamento` INT NOT NULL,
  `id_cargo` INT NOT NULL,
  `id_responsavel_interno` VARCHAR(10) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  PRIMARY KEY (`id_contratos_terceirizados`),
  INDEX `fk_contratos_terceirizados_departamentos1_idx` (`id_departamento` ASC) VISIBLE,
  INDEX `fk_contratos_terceirizados_funcionarios_terceirizados1_idx` (`id_funcionario_terceiro` ASC) VISIBLE,
  INDEX `fk_contratos_terceirizados_cargos1_idx` (`id_cargo` ASC) VISIBLE,
  INDEX `fk_contratos_terceirizados_funcionarios_internos1_idx` (`id_responsavel_interno` ASC) VISIBLE,
  CONSTRAINT `fk_contratos_terceirizados_departamentos1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `gestaodb`.`departamentos` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_terceirizados_funcionarios_terceirizados1`
    FOREIGN KEY (`id_funcionario_terceiro`)
    REFERENCES `gestaodb`.`funcionarios_terceiros` (`id_funcionario_terceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_terceirizados_cargos1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `gestaodb`.`cargos` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_terceirizados_funcionarios_internos1`
    FOREIGN KEY (`id_responsavel_interno`)
    REFERENCES `gestaodb`.`funcionarios_internos` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`visitantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`visitantes` (
  `id_visitante` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `numero_cracha` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_visitante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`visitas` (
  `id_visita` INT NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(50) NOT NULL,
  `timestamp_entrada` DATETIME NOT NULL,
  `timestamp_saida` DATETIME NULL,
  PRIMARY KEY (`id_visita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`visitas_visitantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`visitas_visitantes` (
  `id_visitante` INT NOT NULL,
  `id_visita` INT NOT NULL,
  PRIMARY KEY (`id_visitante`, `id_visita`),
  INDEX `fk_visitas_funcionarios_visitas1_idx` (`id_visita` ASC) VISIBLE,
  CONSTRAINT `fk_visitas_funcionarios_visitantes1`
    FOREIGN KEY (`id_visitante`)
    REFERENCES `gestaodb`.`visitantes` (`id_visitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visitas_funcionarios_visitas1`
    FOREIGN KEY (`id_visita`)
    REFERENCES `gestaodb`.`visitas` (`id_visita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`visitas_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`visitas_funcionarios` (
  `id_visita` INT NOT NULL,
  `id_funcionario` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_visita`, `id_funcionario`),
  INDEX `fk_visitas_funcionarios_funcionarios_internos1_idx` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_visitas_funcionarios_visitas2`
    FOREIGN KEY (`id_visita`)
    REFERENCES `gestaodb`.`visitas` (`id_visita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visitas_funcionarios_funcionarios_internos1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `gestaodb`.`funcionarios_internos` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`visitas_departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`visitas_departamentos` (
  `id_visita` INT NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_visita`, `id_departamento`),
  INDEX `fk_visitas_departamentos_departamentos1_idx` (`id_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_visitas_departamentos_visitas1`
    FOREIGN KEY (`id_visita`)
    REFERENCES `gestaodb`.`visitas` (`id_visita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visitas_departamentos_departamentos1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `gestaodb`.`departamentos` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`projetos_internos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`projetos_internos` (
  `id_projeto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_projeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`projetos_internos_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`projetos_internos_funcionarios` (
  `id_funcionario_interno` VARCHAR(10) NOT NULL,
  `id_projeto_interno` INT NOT NULL,
  `data_inicio` DATE NULL,
  `data_fim` DATE NULL,
  PRIMARY KEY (`id_funcionario_interno`, `id_projeto_interno`),
  INDEX `fk_projetos_internos_funcionarios_projetos_internos1_idx` (`id_projeto_interno` ASC) VISIBLE,
  CONSTRAINT `fk_projetos_internos_funcionarios_funcionarios_internos1`
    FOREIGN KEY (`id_funcionario_interno`)
    REFERENCES `gestaodb`.`funcionarios_internos` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projetos_internos_funcionarios_projetos_internos1`
    FOREIGN KEY (`id_projeto_interno`)
    REFERENCES `gestaodb`.`projetos_internos` (`id_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`registros_de_ponto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`registros_de_ponto` (
  `id_registro_de_ponto` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horario_entrada` TIME NULL,
  `horario_saida` TIME NULL,
  `matricula_funcionario` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_registro_de_ponto`),
  INDEX `fk_registros_de_ponto_funcionarios1_idx` (`matricula_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_registros_de_ponto_funcionarios1`
    FOREIGN KEY (`matricula_funcionario`)
    REFERENCES `gestaodb`.`funcionarios` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`acessos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`acessos` (
  `id_acesso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`id_acesso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestaodb`.`acessos_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestaodb`.`acessos_usuarios` (
  `id_acesso` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_acesso`, `id_usuario`),
  INDEX `fk_acessos_usuarios_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_acessos_usuarios_acessos1`
    FOREIGN KEY (`id_acesso`)
    REFERENCES `gestaodb`.`acessos` (`id_acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acessos_usuarios_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gestaodb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
